add multireader
deislabs/oras pull request #199
Opened 2020-11-10 16:25 UTC by deitch

Provides option to wrap multiple stores to get a single `content.Provider` that can be used anywhere a `Provider` is needed.

2020-11-12 02:40 UTC, jdolitsky requested changes
possible to add unit test?

2020-11-12 09:41 UTC, deitch commented
Yeah, this one, I think, should be doable.

2020-11-12 09:57 UTC, deitch commented
Updated with a test

2020-11-17 17:37 UTC, jdolitsky approved these changes

2020-11-17 17:38 UTC, merged